name: test opencv basic operation

on:
  push:
    branches: ["main"]

jobs:
  Test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: ["3.12", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]
    name: Checking with different python Version ${{matrix.python-version}} sample
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Display Python Version
        run: python --version
          
      - name: execute py script # run main.py
        run: python test.py
  
  Build:
    needs: Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: ["3.12", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]
    name: building different python Version ${{matrix.python-version}} sample
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt
      - name: Display Python Version
        run: python --version 
      - name: build wheel
        run: python -m build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/
      - name: finalizing
        run: |
          echo " build sucessfully created"
    